"""Two RBI-adjacent indicators (Tier 6 item 13's remaining two asks after
forex reserves, see `dtest/data/macro_series.py`), both sourced from FRED
- confirmed live 2026-08-25, needed the Browser pane rather than a direct
`requests`/`curl` call (see "WHY THE BROWSER, NOT REQUESTS" below).

WHY A PROXY, NOT THE LITERAL REPO RATE - RBI's own historical repo-rate
series was never found as a clean, current, machine-readable download
(the Handbook of Statistics XLSX is behind an F5/TSPD bot-detection JS
challenge, RBI's DBIE portal is an Angular SPA needing real JS execution,
and `rbi.org.in`/`data.rbi.org.in` are policy-blocked for this project's
Browser tool entirely - `requests` reaches them fine but only ever sees
the empty app shell or the anti-bot page). Every OECD-MEI-sourced FRED
candidate specifically labeled "Central Bank Rate" for India
(`IRSTCB01INM156N`) or M3 (`MABMM301INM189N`, `MYAGM3INM189N`,
`INDMABMM301IXOBSAM`) stopped updating between 2018 and 2023 - a real,
checked dead end, not an assumption; M3 was dropped from this project's
scope entirely for exactly this reason (see the priority-queue memory,
not repeated here). `IRSTCI01INM156N` (India's overnight call-money/
interbank rate) is the one OECD-sourced India rate series still live
(current through Jun 2026) - RBI's own LAF corridor is explicitly
designed to keep the weighted-average call rate close to the policy repo
rate, so this is a standard, defensible stand-in for repo-rate regime
context, same category of scope substitution as `gsec_yields.py`'s own
3M-interbank stand-in for a missing short-tenor G-Sec yield. Cross-checked
live against RBI's own homepage "Current Rates" widget the same day: Policy
Repo Rate 5.25% vs this series' Jun 2026 reading of 5.50% - close, not
identical, exactly the gap a proxy is expected to have, not a data error.

WHY THE BROWSER, NOT REQUESTS - `fred.stlouisfed.org` was actively
refusing every `requests`/`curl` connection this session
(`ConnectionResetError`/`ReadTimeout`, on both `/graph/fredgraph.csv` and
its own internal `/graph/api/series/` JSON endpoint), while the SAME URLs
load fine in the Browser pane - confirmed a genuine client-side block
(WAF or similar), not a dead host. Fetched via `javascript_tool`
same-origin `fetch()` from within a loaded FRED series page (a plain
browser `navigate()` to the CSV URL itself is blocked as a file
download in this environment, but an in-page `fetch()` call returns the
same CSV text without ever triggering a download) - the resulting text
was pasted directly into this project by hand this session, not
downloaded by a script; `scripts/fetch_gsec_yields.py`'s own direct-
`requests` pattern could NOT be reused here and the two CSVs this module
reads were committed as-is rather than regenerated by a fetch script -
stated plainly, a real deviation from every other source's own-fetch-
script convention in this project.

Bank credit: `CRDQINBPABIS` (BIS, not OECD MEI - a more reliably
maintained source family, confirmed live through Q4 2025), "Credit to
Private Non-Financial Sector by Domestic Banks, Adjusted for Breaks" -
billions of Rupees, quarterly, real depth back to Q2 1951.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

REPO_RATE_PROXY_SCHEMA = {"date": "datetime64[ns]", "call_money_rate_pct": "float64"}
BANK_CREDIT_SCHEMA = {"date": "datetime64[ns]", "credit_rs_bn": "float64"}


def _empty(schema: dict[str, str]) -> pd.DataFrame:
    return pd.DataFrame({c: pd.Series(dtype=t) for c, t in schema.items()})


def load_repo_rate_proxy(rbi_rates_credit_dir: Path) -> pd.DataFrame:
    """India overnight call-money/interbank rate (FRED `IRSTCI01INM156N`) -
    a proxy for RBI's policy repo rate, not the literal announced rate.
    See the module docstring's "WHY A PROXY" section."""
    path = Path(rbi_rates_credit_dir) / "IRSTCI01INM156N.csv"
    if not path.exists():
        return _empty(REPO_RATE_PROXY_SCHEMA)
    df = pd.read_csv(path, parse_dates=["observation_date"])
    df = df.rename(columns={"observation_date": "date", "IRSTCI01INM156N": "call_money_rate_pct"})
    return df.sort_values("date", kind="stable").reset_index(drop=True)[list(REPO_RATE_PROXY_SCHEMA)]


def load_bank_credit(rbi_rates_credit_dir: Path) -> pd.DataFrame:
    """Credit to India's private non-financial sector by domestic banks
    (FRED `CRDQINBPABIS`, BIS-sourced), quarterly, billions of Rupees."""
    path = Path(rbi_rates_credit_dir) / "CRDQINBPABIS.csv"
    if not path.exists():
        return _empty(BANK_CREDIT_SCHEMA)
    df = pd.read_csv(path, parse_dates=["observation_date"])
    df = df.rename(columns={"observation_date": "date", "CRDQINBPABIS": "credit_rs_bn"})
    return df.sort_values("date", kind="stable").reset_index(drop=True)[list(BANK_CREDIT_SCHEMA)]
